### ISSUE TITLE
Обновление генератора для генерации enum из различных пакетов

### ISSUE THREAD

**Issue by vadim-aura** [AURA-Devices/blerpc-android#17]
Когда появляется дополнительный пакет на пример package aura.common; и данный пакет используется в другом пакете например package aura.devices;, тогда происходит задвоение пакетов в имени класса объекта например Aura_Devices_Aura_Common_Enum, а должно быть Aura_Common_Enum браться только пакет класса и исключаться пакет класса сервиса использующего данный класс.

**Comment by Nikolas-LFDesigns** [comment]
related: https://github.com/AURA-Devices/blerpc-android/issues/12
